<!-- Fichier a placer dans le répertoire www au même niveau que l'autre layout -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Admin</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
    <main>
        <!-- Affichage du template lié à la vue -->
        <?php include $this->viewData['template'] ?>
    </main>
</body>
</html>