<!DOCTYPE html>
<html lang="fr">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Admin - Cupoftee</title>

    <!-- Bootstrap core CSS -->
    <link href="<?= $wwwUrl?>/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

     <!-- FONTAwesome core CSS -->
     <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.0/css/all.css" integrity="sha384-aOkxzJ5uQz7WBObEZcHvV5JvRW3TUc2rNPA7pe3AwnsUohiw1Vj2Rgx2KSOkF5+h" crossorigin="anonymous">

    <!--Datatable -->
    <link href="http://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet">

    <script src='https://cloud.tinymce.com/stable/tinymce.min.js'></script>

  </head>

  <body>

    <!--Navigation-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
      <div class="container">
        <a class="navbar-brand" href="<?= $requestUrl ?>/admin/categories/">GEstion des thés</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="<?= $requestUrl ?>/admin/categories/">Home
                <span class="sr-only">(current)</span>
              </a>
            </li>
            
             <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="listUser.php" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Produits
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="listArticle.php">Liste</a>
                <a class="dropdown-item" href="addArticle.php">Ajouter</a>
              </div>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="listUser.php" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Catégorie
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="listCategory.php">Liste</a>
                <a class="dropdown-item" href="<?= $requestUrl ?>/admin/categories/AddCategories">Ajouter</a>
              </div>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="listUser.php" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Utilisateurs
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="listCategory.php">Liste</a>
                <a class="dropdown-item" href="addCategory.php">Ajouter</a>
              </div>
            </li>
             <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="listUser.php" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              </a>
               <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="logout.php">Déconnexion</a>
              </div>
              </li>
          
          </ul>
      
        </div>
      </div>
    </nav>

    <!-- Page Content -->
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <h1 class="mt-5">Gestion</h1>
          <?php 
          if(isset($flashbag) && $flashbag!=false):
            foreach($flashbag as $message):?>
              <div class="alert alert-success"><?=$message?></div>
          <?php
            endforeach;
          endif;
          ?>
         
          <?php 
          include $this->viewData['template']?>
        </div>
      </div>
    </div>

    <div class="modal fade" id="delete" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Suppression</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            Êtes-vous sûr de vouloir supprimer cet element ?
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <a id="linkdelete" href="#"><button type="button" class="btn btn-primary">Supprimer</button></a>
          </div>
        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript -->
    <script src="<?= $wwwUrl?>/vendor/jquery/jquery.min.js"></script>
    <script src="<?= $wwwUrl?>/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="http://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    
    <!-- Data Table -->
    <script>
        $(document).ready( function () {
            $('#tableDonnee').DataTable();
        });
        $('#delete').on('show.bs.modal', function (e) {
          $('#linkdelete').attr("href", e.relatedTarget.href);
          //$('#linkdelete').href =  e.relatedTarget.href;
        });
    </script>

  </body>

</html>