<!-- PAGE D'AJOUT D'UNE CATEGORIE-->
<section>
<!-- FORMULAIRE -->
<form method="POST" action="<?= $requestUrl; ?>/admin/categories/editcategorie" enctype="multipart/form-data">
  


    <input type="hidden" name="id" value="<?= $categorie['idcategories']?>" />
    <input type="text" name="titreCategorie" id="titreCategorie" placeholder="Nom de la nouvelle Catégorie" value="<?= $categorie['categorie_name']?>">
   
    <input type="textarea" name="descriptionCategorie" id="descriptionCategorie" placeholder="Description de la Categorie"  value="<?= $categorie['categorie_description']?>">

    <label for="imageCategorie">Fichier:</label>
    <input type="hidden" name="imageOriginale" value="<?= $categorie['categorie_picture']; ?>">
     <input type="hidden" name="MAX_FILE_SIZE" value="1048576" />
     <input type="file" name="imageCategorie" id="imageCategorie" accept="image/png,image/jpeg,image/gif"/>
     <input type="submit" value="soumettre l'article">
    </form>
</section>